### ISSUE TITLE
JBrowse Broken with last update

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/serratus.io#105]
With the most recent production update it looks like JBrowse bit the big one and is no longer willing to load any data.

See: https://serratus.io/jbrowse?bam=SRR057961&loc=JQ173883.1

No clue on what could be causing this :(

**Comment by victorlin** [comment]
The problem is apparent in the developer console:

> Access to fetch at 'https://lovelywater.s3.amazonaws.com/seq/cov3ma/cov3ma.fa.fai' from origin 'https://serratus.io' has been blocked by CORS policy

This is the current policy at lovelywater > Permissions > **Cross-origin resource sharing (CORS)**:

```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "https://*.serratus.io"
        ],
        "ExposeHeaders": []
    }
]
```

@ababaian could you update `AllowedOrigins` to this?

```json
"AllowedOrigins": [
    "https://serratus.io",
    "https://*.serratus.io"
]
```

Or, simply `"AllowedOrigins": [ "*" ]` if we want to be liberal and allow any programmatic web access [[doc](https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html#cors-allowed-origin)].

**Comment by ababaian** [comment]
Shes' good :+1:
