### ISSUE TITLE
RdRP Explorer: Reset default "score" to 0-100 when viewing a single SRA run

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/serratus.io#161]
I forgot when but we updated the default display behaviour of the RdRP Explorer so that it displays only Score 50-100 results. When doing a "virus family" search this makes alot of sense, the low-score stuff is more likely to contain noise afterall.

The issue arises when you navigate to an SRA run after say changing the score threshold or if you are linked to it from an RdRP link in PalmID. The default score of 50 hides many of the viral hits and it says "No Data Found" (https://serratus.io/explorer/rdrp?run=SRR10024069). This is kind of misleading since there is data, it just isn't being displayed.

For 'Family' or 'GenBank' search I like having a default score of 50. For lookup of a specific SRA run, thedefault should be 0 and all results are shown.

**Comment by victorlin** [comment]
This is due to the default slider values:

https://github.com/serratus-bio/serratus.io/blob/f742dcba2e2f2604497231f539f572d64bbafc9b/src/components/Explorer/Rdrp/RdrpExplorer.tsx#L30-L32

Currently they are shared between search levels. With some tweaking, we should be able to set defaults for each level. I'll take a look at this.
