### ISSUE TITLE
"No viral RdRP identified in input sequence (or a server error occured)"

### ISSUE THREAD

**Issue by murrellb** [serratus-bio/serratus.io#193]
Might be a bug - not 100% sure. I downloaded the Paramyxoviridae RdRp MSA file (from here: https://serratus.io/trees), and took one of the sequences (u5506):

```
>test_u5506
LTTDLQKYCLNWRYPTIKLFAMKLNQILGIPHGFEWIHLRLRDTTMFVGDPYNPPNDINFINLDDQKNDSIFIVSPRGGIEGLCQKMWTMISISAIHLSATKTGCRVASMVQGDNQAI
```

and uploaded it to https://serratus.io/palmid

Which gives me the following error:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1152087/183651280-65de8a0e-4ec9-496c-be05-7d975bad76e9.png">

I've previously done this for other RdRp sequences, and it worked fine, but it doesn't seem to work for any Paramyxoviridae sequences I've tried.

**Comment by ababaian** [comment]
Much apologies @murrellb about the delay. I've been on a bit of a snooze over summer.

Anyways, the problem was localized to the `palmid.Rmd` script
```
Quitting from lines 65-148 (palmid.Rmd)
Error in if (!all(palm.geo.tmp$biosample_id == palm.sra$biosample_id)) { :
```

It appears there were some SRA accessions which did not contain a valid `biosample` ID. This shouldn't be the case. For some reason a handful of datasets which contain [measles](https://www.ncbi.nlm.nih.gov/sra/?term=ERR3822204) did not contain a BioSample identifier, I went in and fixed this manually in the database and everything is working. Anytime these measles datasets were being retrieved it would end up stalling, thus a bunch of `Paramyxoviridae` were not accessible. Strange bug, but easy fix.

Here is your virus report for [`taxpayingPension` virus (u5506)](https://serratus.io/palmid?hash=bcc7ab039aaf2b3a655d719677e4d7e339855a0f). Please let me know if I can help (and it should be quicker this time).
